In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
df=pd.read_csv(r"C:\Users\Aminu Ibrahim\Desktop\EDA Project\nigeria_food_prices_practice.csv")
df

           date      state                item price_ngn  markets_surveyed
0    2025-11-01    Anambra         Beans (1kg)    2708.4              31.0
1    2023-06-01       Kano   Tomatoes (basket)   8871.24              25.0
2    2024-06-01        Oyo         Garri (1kg)    711.89              14.0
3    2025-07-01      Enugu  Vegetable oil (1L)   3734.86              37.0
4    2023-09-01    Anambra  Vegetable oil (1L)   2428.03               NaN
..          ...        ...                 ...       ...               ...
970  2024-09-01       Kano         Garri (1kg)    824.78              19.0
971  2024-11-01       Kano          Rice (1kg)   1505.74              11.0
972  2024-07-01  Abuja FCT  Vegetable oil (1L)   3186.72              33.0
973  2024-08-01    Anambra         Beans (1kg)   1696.93              39.0
974  2023-07-01     Rivers         Garri (1kg)    619.78              30.0

[975 rows x 5 columns]

In [3]:
df.isna().sum

<bound method DataFrame.sum of       date  state   item  price_ngn  markets_surveyed
0    False  False  False      False             False
1    False  False  False      False             False
2    False  False  False      False             False
3    False  False  False      False             False
4    False  False  False      False              True
..     ...    ...    ...        ...               ...
970  False  False  False      False             False
971  False  False  False      False             False
972  False  False  False      False             False
973  False  False  False      False             False
974  False  False  False      False             False

[975 rows x 5 columns]>

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 975 entries, 0 to 974
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date              975 non-null    str
 1   state             975 non-null    str
 2   item              975 non-null    str
 3   price_ngn         933 non-null    str
 4   markets_surveyed  949 non-null    float64
dtypes: float64(1), str(4)
memory usage: 38.2 KB

In [5]:
df.head()

         date    state                item price_ngn  markets_surveyed
0  2025-11-01  Anambra         Beans (1kg)    2708.4              31.0
1  2023-06-01     Kano   Tomatoes (basket)   8871.24              25.0
2  2024-06-01      Oyo         Garri (1kg)    711.89              14.0
3  2025-07-01    Enugu  Vegetable oil (1L)   3734.86              37.0
4  2023-09-01  Anambra  Vegetable oil (1L)   2428.03               NaN

In [6]:
df.describe(include='all')

              date    state         item price_ngn  markets_surveyed
count          975      975          975       933        949.000000
unique          36       17            6       919               NaN
top     2023-10-01  Anambra  Garri (1kg)   1294.72               NaN
freq            34      129          175         3               NaN
mean           NaN      NaN          NaN       NaN         22.100105
std            NaN      NaN          NaN       NaN         10.055935
min            NaN      NaN          NaN       NaN          5.000000
25%            NaN      NaN          NaN       NaN         13.000000
50%            NaN      NaN          NaN       NaN         22.000000
75%            NaN      NaN          NaN       NaN         31.000000
max            NaN      NaN          NaN       NaN         39.000000

In [7]:
df.shape

(975, 5)

In [8]:
df_clean= df.drop_duplicates()
df_clean

           date      state                item price_ngn  markets_surveyed
0    2025-11-01    Anambra         Beans (1kg)    2708.4              31.0
1    2023-06-01       Kano   Tomatoes (basket)   8871.24              25.0
2    2024-06-01        Oyo         Garri (1kg)    711.89              14.0
3    2025-07-01      Enugu  Vegetable oil (1L)   3734.86              37.0
4    2023-09-01    Anambra  Vegetable oil (1L)   2428.03               NaN
..          ...        ...                 ...       ...               ...
970  2024-09-01       Kano         Garri (1kg)    824.78              19.0
971  2024-11-01       Kano          Rice (1kg)   1505.74              11.0
972  2024-07-01  Abuja FCT  Vegetable oil (1L)   3186.72              33.0
973  2024-08-01    Anambra         Beans (1kg)   1696.93              39.0
974  2023-07-01     Rivers         Garri (1kg)    619.78              30.0

[960 rows x 5 columns]

In [9]:
df_clean.shape

(960, 5)

In [10]:
df_clean.duplicated().sum()

np.int64(0)

In [11]:
df_clean.head(10)

         date      state                item price_ngn  markets_surveyed
0  2025-11-01    Anambra         Beans (1kg)    2708.4              31.0
1  2023-06-01       Kano   Tomatoes (basket)   8871.24              25.0
2  2024-06-01        Oyo         Garri (1kg)    711.89              14.0
3  2025-07-01      Enugu  Vegetable oil (1L)   3734.86              37.0
4  2023-09-01    Anambra  Vegetable oil (1L)   2428.03               NaN
5  2025-01-01  Abuja FCT        Eggs (crate)   4623.09               5.0
6  2023-10-01  Abuja FCT         Beans (1kg)   1268.79              23.0
7  2025-10-01     Kaduna  Vegetable oil (1L)   4263.18              34.0
8  2025-01-01  Abuja FCT   Tomatoes (basket)  19609.06              17.0
9  2023-06-01       Kano          Rice (1kg)   1038.35              32.0